import type { Metadata } from "next";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"
import localFont from "next/font/local";
import "./globals.css";

const fcVisionRounded = localFont({
  src: "./fonts/FC Vision Rounded.otf",
  variable: "--font-fc-vision-rounded",
  weight: "400 700",
});
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${fcVisionRounded.variable} ${fcVisionRounded.variable} antialiased`}
      >
        <SidebarProvider className="overflow-hidden">
          <AppSidebar />
          <main>
            <SidebarTrigger className="absolute" />
            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
